[workspace]
members = [
    "userspace/esp-tools",
    "userspace/esp-runtime",
    "userspace/esuinit",
]
default-members = [
    "userspace/esp-tools",
    "userspace/esp-runtime",
    "userspace/esuinit",
]
resolver = "3"
exclude = ["out", "vendor"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
anyhow = "1"
log = "0.4"
libc = "0.2"

[patch.crates-io]
libc = { git = "https://github.com/rust-lang/libc", rev = "1a661633f11a261ff9c00b40875ef72f1cbec818" }

[profile.release]
strip = true
lto = true
opt-level = "z"
panic = "abort"

