[workspace]
members = [
    "userspace/esud",
    "userspace/esuinit",
    "userspace/dm",
    "userspace/lvm2-meta",
    "userspace/thin-activate",
    "userspace/fw-views",
    "userspace/avb-graft",
    "userspace/avb-graft-cli",
    "userspace/esu-platform",
    "userspace/esu-config",
    "userspace/ota-core",
    "userspace/abl-image",
]
default-members = [
    "userspace/esud",
    "userspace/esuinit",
    "userspace/dm",
    "userspace/lvm2-meta",
    "userspace/thin-activate",
    "userspace/fw-views",
    "userspace/avb-graft",
    "userspace/avb-graft-cli",
    "userspace/esu-config",
    "userspace/ota-core",
    "userspace/abl-image",
]
resolver = "3"
exclude = ["esu/modules/boot-hal/layer", "esu/modules/boot-hal/generic-bootctl"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
anyhow = "1"
log = "0.4"
libc = "0.2"

[patch.crates-io]
libc = { git = "https://github.com/rust-lang/libc", rev = "1a661633f11a261ff9c00b40875ef72f1cbec818" }

[profile.release]
strip = true
lto = true
opt-level = "z"
panic = "abort"

[profile.release.package.esud]
codegen-units = 1
