espinit-objs := core/init.o

espinit-objs += feature/kernel_umount.o
espinit-objs += feature/selinux_hide.o

espinit-objs += hook/lsm_hook.o
espinit-objs += hook/setuid_hook.o
espinit-objs += hook/syscall_event_bridge.o
espinit-objs += hook/syscall_hook_manager.o
espinit-objs += hook/tp_marker.o
ifeq ($(CONFIG_ARM64),y)
espinit-objs += hook/arm64/patch_memory.o
espinit-objs += hook/arm64/syscall_hook.o
else ifeq ($(CONFIG_X86_64),y)
espinit-objs += hook/x86_64/patch_memory.o
espinit-objs += hook/x86_64/syscall_hook.o
else ifeq ($(CONFIG_RISCV),y)
espinit-objs += hook/riscv64/patch_memory.o
espinit-objs += hook/riscv64/syscall_hook.o
endif

espinit-objs += infra/file_wrapper.o
espinit-objs += infra/symbol_resolver.o

espinit-objs += policy/feature.o

espinit-objs += runtime/boot_event.o
espinit-objs += runtime/ksud_integration.o

espinit-objs += selinux/selinux.o
espinit-objs += selinux/rules.o
espinit-objs += selinux/sepolicy.o

espinit-objs += supercall/dispatch.o
espinit-objs += supercall/perm.o
espinit-objs += supercall/supercall.o

ifdef KBUILD_EXTMOD
ifeq ($(CONFIG_ESPINIT_DEBUG),y)
ccflags-y += -DCONFIG_ESPINIT_DEBUG=1
endif
ifeq ($(CONFIG_ESPINIT_X86_PATCH_SYSCALL_DISPATCHER),y)
ccflags-y += -DCONFIG_ESPINIT_X86_PATCH_SYSCALL_DISPATCHER=1
endif
endif

ccflags-y += -I$(srctree)/security/selinux -I$(srctree)/security/selinux/include
ccflags-y += -I$(objtree)/security/selinux -include $(srctree)/include/uapi/asm-generic/errno.h

ifneq ($(KBUILD_EXTMOD),)
# 6.18 exports the external module source as srcroot when M/MO are used.
ifneq ($(srcroot),)
KSU_KERNEL_DIR := $(srcroot)
endif
endif
ifndef KSU_KERNEL_DIR
ifeq ($(filter /%,$(src)),)
KSU_KERNEL_DIR := $(srctree)/$(src)
else
KSU_KERNEL_DIR := $(src)
endif
endif

ccflags-y += -I$(KSU_KERNEL_DIR) -I$(KSU_KERNEL_DIR)/include

obj-$(CONFIG_ESPINIT) += espinit.o

MDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

# Workaround bazel
# https://github.com/tiann/KernelSU/pull/316#issuecomment-1479043219
GIT := $(shell PATH="$$PATH":/usr/bin:/usr/local/bin which git)
ifneq ($(GIT),)
# Check if this is a git repository
# Try to detect Git repo intelligently
GIT_ROOT := $(shell cd $(MDIR) && $(GIT) rev-parse --show-toplevel 2>/dev/null)
ifneq ($(GIT_ROOT),)
KERNEL_GIT_ROOT := $(shell cd $(srctree) && $(GIT) rev-parse --show-toplevel 2>/dev/null)
ifneq ($(GIT_ROOT),$(KERNEL_GIT_ROOT))
# Only set version if it's a different repo from kernel
$(shell cd $(GIT_ROOT) && [ -f .git/shallow ] && $(GIT) fetch --unshallow 2>/dev/null || true)
KSU_GIT_VERSION := $(shell cd $(GIT_ROOT) && $(GIT) rev-list --count HEAD 2>/dev/null)
KSU_GIT_VERSION_VALID := 1
$(info -- espinit: Git repo detected at $(GIT_ROOT))
endif
endif
else
$(warning -- espinit: Git not detected, make sure git is installed in your PATH!)
endif


# Calculate version if git version is available
ifdef KSU_GIT_VERSION_VALID
# ksu_version: major * 10000 + git version + 200 for historical reasons
$(eval KSU_VERSION=$(shell expr 30000 + $(KSU_GIT_VERSION)))
$(info -- espinit version: $(KSU_VERSION))
ccflags-y += -DKSU_VERSION=$(KSU_VERSION)
else
# If there is no .git directory, use default version
$(warning "KSU_GIT_VERSION not defined! It is better to make espinit a git repository!")
ccflags-y += -DKSU_VERSION=16
endif

KSU_NEW_DCACHE_FLUSH := $(shell grep -q __flush_dcache_area $(srctree)/arch/arm64/include/asm/cacheflush.h ; echo $$?)
$(info -- KSU_NEW_DCACHE_FLUSH: $(KSU_NEW_DCACHE_FLUSH))



ccflags-y += -DKSU_NEW_DCACHE_FLUSH=$(KSU_NEW_DCACHE_FLUSH)

ccflags-y += -Wno-strict-prototypes -Wno-int-conversion -Wno-gcc-compat -Wno-missing-prototypes
ccflags-y += -Wno-declaration-after-statement -Wno-unused-function

# Keep a new line here!! Because someone may append config
