[package]
name = "esud"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "esud"
path = "src/main.rs"

[target.'cfg(target_os = "linux")'.dependencies]
esuinit = { path = "../esuinit" }
goblin = "0.10"
libc.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.11"
tempfile = "3"

[dependencies]
esu-platform = { path = "../esu-platform" }
esu-config = { path = "../esu-config" }
ota-core = { path = "../ota-core" }
anyhow.workspace = true
clap = { version = "4", features = ["derive"] }
const_format = "0.2"
log.workspace = true
nom = "8"
derive-new = "0.7"

[target.'cfg(target_os = "android")'.dependencies]
rustix = { version = "1", features = [
    "all-apis",
] }
android_logger = { version = "0.15", default-features = false }
libc = "0.2"
extattr = "1"
esuinit = { path = "../esuinit" }
prop-rs-android = { git = "https://github.com/KernelSU2/ksu_props", rev = "ddb6ee7294467f7f25bad2118e9e24eee104144b" }

[dev-dependencies]
tempfile = "3"

[target.'cfg(target_os = "linux")'.dev-dependencies]
lz4 = "1.28"

[build-dependencies]
bindgen = "0.72"
