name: Build

on:
  push:
    branches: [main, dev, ci]
    paths: ['.github/**', 'kernel/**', 'uapi/**', 'userspace/**', 'scripts/**', 'patches/**', 'vendor/Magisk', 'Cargo.toml', 'Cargo.lock']
  pull_request:
    branches: [main, dev]
    paths: ['.github/**', 'kernel/**', 'uapi/**', 'userspace/**', 'scripts/**', 'patches/**', 'vendor/Magisk', 'Cargo.toml', 'Cargo.lock']
  workflow_call:

permissions:
  contents: read

jobs:
  build-init:
    uses: ./.github/workflows/init.yml
  build-native:
    strategy:
      matrix:
        abi: [arm64-v8a, x86_64]
    uses: ./.github/workflows/daemon.yml
    with:
      abi: ${{ matrix.abi }}
  build-host:
    uses: ./.github/workflows/daemon-extra.yml
