name: Build

on:
  push:
    branches: [ "main", "dev", "ci" ]
    paths:
      - '.github/workflows/build.yml'
      - '.github/workflows/build-lkm.yml'
      - '.github/workflows/ddk-lkm.yml'
      - '.github/workflows/daemon.yml'
      - '.github/workflows/daemon-extra.yml'
      - '.github/workflows/init.yml'
      - '.github/scripts/setup-rust-build.sh'
      - '.github/riscv64-cargo.toml'
      - 'kernel/**'
      - 'userspace/**'
      - 'Cargo.lock'
      - 'Cargo.toml'
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - '.github/workflows/build.yml'
      - '.github/workflows/build-lkm.yml'
      - '.github/workflows/ddk-lkm.yml'
      - '.github/workflows/daemon.yml'
      - '.github/workflows/daemon-extra.yml'
      - '.github/workflows/init.yml'
      - '.github/scripts/setup-rust-build.sh'
      - '.github/riscv64-cargo.toml'
      - 'kernel/**'
      - 'userspace/**'
      - 'Cargo.lock'
      - 'Cargo.toml'
  workflow_call:

permissions:
  contents: read

jobs:
  build-lkm:
    uses: ./.github/workflows/build-lkm.yml

  build-init:
    uses: ./.github/workflows/init.yml

  build-daemon:
    strategy:
      matrix:
        include:
          - target: aarch64-linux-android
          - target: x86_64-linux-android
          - target: riscv64-linux-android
    uses: ./.github/workflows/daemon.yml
    with:
      target: ${{ matrix.target }}

  build-daemon-extra:
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-gnu # windows pc
            os: ubuntu-latest
          - target: x86_64-apple-darwin # Intel mac
            os: macos-latest
          - target: aarch64-apple-darwin # M chip mac
            os: macos-latest
          - target: aarch64-unknown-linux-musl # arm64 Linux
            os: ubuntu-latest
          - target: x86_64-unknown-linux-musl # x86 Linux
            os: ubuntu-latest
    uses: ./.github/workflows/daemon-extra.yml
    with:
      target: ${{ matrix.target }}
      os: ${{ matrix.os }}
