name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
  release:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8

      - name: Rename espinitd
        run: |
          mkdir -p espinitd
          for dir in ./espinitd-*; do
            if [ -d "$dir" ]; then
                echo "----- Rename $dir -----"
                espinitd_platform_name=$(basename "$dir")
                if [ -f "$dir/espinitd" ]; then
                  mv "$dir/espinitd" "espinitd/$espinitd_platform_name"
                elif [ -f "$dir/espinitd.exe" ]; then
                  mv "$dir/espinitd.exe" "espinitd/$espinitd_platform_name.exe"
                fi
            fi
          done

      - name: Rename espinit
        run: |
          mkdir -p espinit
          for dir in ./espinit-*; do
            if [ -d "$dir" ]; then
                echo "----- Rename $dir -----"
                espinit_platform_name=$(basename "$dir")
                if [ -f "$dir/espinit" ]; then
                  mv "$dir/espinit" "espinit/$espinit_platform_name"
                fi
            fi
          done

      - name: Rename phone LVM activator
        run: |
          mkdir -p thin-activate
          mv ./espinit-aarch64/thin-activate \
            thin-activate/thin-activate-aarch64-linux-android

      - name: Rename lkm
        run: |
          mkdir -p lkm
          for dir in ./*-android*-espinit-lkm; do
            if [ -d "$dir" ]; then
                echo "----- Rename $dir -----"
                lkm_platform_name=$(basename "$dir")
                lkm_target="${lkm_platform_name%-espinit-lkm}"
                lkm_kmi="${lkm_target#*-}"
                mv "$dir/${lkm_kmi}_espinit.ko" "lkm/lkm-${lkm_target}_espinit.ko"
            fi
          done

      - name: Display structure of downloaded files
        run: ls -R

      - name: release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            espinit/*
            espinitd/*
            thin-activate/*
            lkm/lkm-*_espinit.ko
